name = "cf-worker-aws1" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]] 
pattern = "aws1.speedwifi.ggff.net"
custom_domain = true 
[[routes]] 
pattern = "images-digital.maxis.com.my.aws1.speedwifi.ggff.net"
custom_domain = true 
[[routes]] 
pattern = "care.maxis.com.my.aws1.speedwifi.ggff.net"
custom_domain = true 


[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "08f344e3-700e-4333-b662-ca6ff66de50c"
